version: '2.2'

services:
  web:
    image: trydirect/status:latest
    container_name: status
    ports:
     - "5001:5000"
    volumes:
     - .:/app
     - /var/run/docker.sock:/var/run/docker.sock
#     - /data/encrypted:/data/encrypted
    env_file:
      - .env
    environment:
      - NGINX_CONTAINER=nginx
