version: '2.2'

services:
  statuspanel:
    image: trydirect/status:latest
    container_name: statuspanel
    ports:
     - "5001:5000"
    volumes:
     - .:/app
     - /var/run/docker.sock:/var/run/docker.sock
#     - /data/encrypted:/data/encrypted
    entrypoint: [""]
#    command: ["bash", "-c", "sleep infinity"]
    env_file:
      - .env
    environment:
      - NGINX_CONTAINER=nginx
