version: '2.2'

services:
  web:
    image: optimum/try.direct:agent
    build:
     context: .
    container_name: try.direct.agent
    ports:
     - "5000:5000"
    volumes:
     - .:/app
     - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - NGINX_CONTAINER=nginx
