name: Docker CI/CD

on:
  push:
    branches:
      - master
      - production
      - testing
  pull_request:
    branches:
      - master

jobs:
  docker-dev-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.prod
          push: true
          tags: trydirect/status:${{ steps.vars.outputs.short_ref }}